import streamlit as st
import random

motivational_quotes = [
    "Believe you can and you're halfway there.",
    "The only way to do great work is to love what you do.",
    "Don't watch the clock; do what it does. Keep going.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "Your time is limited, don't waste it living someone else's life.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Don't stop when you're tired. Stop when you're done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Little things make big days.",
    "It's going to be hard, but hard does not mean impossible.",
    "Don't wait for opportunity. Create it.",
    "Sometimes we're tested not to show our weaknesses, but to discover our strengths.",
    "The key to success is to focus on goals, not obstacles.",
    "Dream it. Wish it. Do it.",
    "Great things never come from comfort zones.",
    "Push yourself, because no one else is going to do it for you.",
    "Success doesn't just find you. You have to go out and get it.",
    "The harder the struggle, the more glorious the triumph.",
    "Don't limit your challenges. Challenge your limits.",
    "Keep going. Everything you need will come to you at the perfect time.",
    "Do something today that your future self will thank you for.",
    "Little by little, a little becomes a lot.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "Success is not in what you have, but who you are.",
    "Act as if what you do makes a difference. It does.",
    "If you want it, work for it.",
    "You don’t have to be great to start, but you have to start to be great.",
    "Don’t wait. The time will never be just right.",
    "Strive for progress, not perfection.",
    "Doubt kills more dreams than failure ever will.",
    "Your limitation—it’s only your imagination.",
    "Great things take time.",
    "Don’t let yesterday take up too much of today.",
    "You are capable of amazing things.",
    "The expert in anything was once a beginner.",
    "Focus on your goal. Don’t look in any direction but ahead.",
    "Do what you can with what you have, where you are.",
    "Believe in yourself and all that you are.",
    "Success is the sum of small efforts repeated day in and day out.",
    "The best way to get started is to quit talking and begin doing.",
    "You are stronger than you think.",
    "Push yourself because no one else is going to do it for you.",
    "Work hard in silence, let success be your noise.",
    "Opportunities don't happen. You create them.",
    "Don’t be afraid to give up the good to go for the great.",
    "I find that the harder I work, the more luck I seem to have.",
    "Success usually comes to those who are too busy to be looking for it.",
    "The road to success and the road to failure are almost exactly the same.",
    "Don’t let what you cannot do interfere with what you can do.",
    "Try not to become a man of success. Rather become a man of value.",
    "Motivation is what gets you started. Habit is what keeps you going.",
    "You don’t have to see the whole staircase, just take the first step.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Do one thing every day that scares you.",
    "Don’t quit. Suffer now and live the rest of your life as a champion.",
    "The future depends on what you do today.",
    "Fall seven times and stand up eight.",
    "It always seems impossible until it’s done.",
    "Action is the foundational key to all success.",
    "Don’t let fear of losing be greater than the excitement of winning.",
    "If you can dream it, you can do it.",
    "Keep your eyes on the stars, and your feet on the ground.",
    "Don’t count the days. Make the days count.",
    "Make each day your masterpiece.",
    "The way to get started is to quit talking and begin doing.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Hardships often prepare ordinary people for an extraordinary destiny.",
    "Don’t wait for the perfect moment. Take the moment and make it perfect.",
    "Everything you’ve ever wanted is on the other side of fear.",
    "If it doesn’t challenge you, it won’t change you.",
    "The secret of getting ahead is getting started.",
    "You are your only limit.",
    "Do not stop thinking of life as an adventure.",
    "The difference between ordinary and extraordinary is that little extra.",
    "Difficulties in life don’t come to destroy you, but to help you realize your hidden potential.",
    "Start where you are. Use what you have. Do what you can.",
    "Don’t watch the clock; do what it does. Keep going.",
    "Keep your face always toward the sunshine—and shadows will fall behind you.",
    "Success is liking yourself, liking what you do, and liking how you do it.",
    "You miss 100% of the shots you don’t take.",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "Push yourself, because no one else is going to do it for you.",
    "Stay positive, work hard, make it happen."
]


if st.button("Stay motivated!"):
    quote = random.choice(motivational_quotes)
    quote2 = random.choice(motivational_quotes)
    st.success(quote)
    st.toast(quote2, icon="💡")
